#!/usr/bin/env python3
"""One-time seed for data/publications.json from the live site. After this,
use site.py to add publications. Each entry has: num (int or null for
preprints), year, title, authors, venue, and links [{label,url}]. The renderer
bolds 'Beliveau' automatically.
"""
import json, pathlib

def L(*pairs): return [{"label": l, "url": u} for l, u in pairs]

preprints = [
 {"title": "Nascent transcript O-MAP reveals the molecular architecture of a single-locus subnuclear compartment built by RBM20 and the TTN RNA",
  "authors": "Kania, E.E., Fenix, A., Marciniak, D.M., Lin, Q., Bianchi, S., Hristov, B., Li, S., Camplisson, C.K., Fields, R., Beliveau, B.J., Schweppe, D.K., Noble, W.S., Ong, S.E., Berero, A.†, Murry, C.E.†, Shechner, D.M.†",
  "venue": "bioRxiv (2024)",
  "links": L(("Preprint", "https://www.biorxiv.org/content/10.1101/2024.11.05.622011v1"), ("PDF", "https://www.biorxiv.org/content/10.1101/2024.11.05.622011v1.full.pdf"))},
 {"title": "DNA O-MAP uncovers the molecular neighborhoods associated with specific genomic loci",
  "authors": "Liu, Y.*, McGann, C.D.*, Krebs, M., Perkins Jr., T.A., Fields, R., Camplisson, C.K., Nwizugbo, D.Z., Hsu, C., Avanessian, S.C., Tsue, A.F., Kania, E.E., Shechner, D.M., Beliveau, B.J.†, Schweppe, D.K.†",
  "venue": "eLife (2024)",
  "links": L(("Reviewed preprint", "https://elifesciences.org/reviewed-preprints/102489"), ("PDF", "https://www.biorxiv.org/content/10.1101/2024.07.24.604987v3.full.pdf"), ("SI", "https://www.biorxiv.org/content/10.1101/2024.07.24.604987v3.supplementary-material"))},
 {"title": "Harmonizing the Generation and Pre-publication Stewardship of FAIR Image Data",
  "authors": "Bialy, N., Alber, F., Andrews, B., Angelo, M., Beliveau, B., Bintu, L., Boettiger, A., Boehm, U., Brown, C.M., et al.",
  "venue": "arXiv (2024)",
  "links": L(("Preprint", "https://arxiv.org/abs/2401.13022"), ("PDF", "https://arxiv.org/pdf/2401.13022.pdf"))},
 {"title": "Quantitative multiplexed imaging of chromatin ultrastructure with Decode-PAINT",
  "authors": "Sasaki, H.M., Kishi, J.Y., Wu, C.-T., Beliveau, B.J.†, Yin, P.†",
  "venue": "bioRxiv (2022)",
  "links": L(("Preprint", "https://www.biorxiv.org/content/10.1101/2022.08.01.502089v1"), ("PDF", "https://www.biorxiv.org/content/10.1101/2022.08.01.502089v1.full.pdf"), ("SI", "https://www.biorxiv.org/content/10.1101/2022.08.01.502089v1.supplementary-material"))},
]

papers = [
 (36, 2025, "Performing SABER-FISH on Chromosome Spreads in Fixed Tissue Culture Cells and in Tissues",
  "Attar, S.*, Krebs, M.*, Nichols, E.K., Akliesh, S., Beliveau, B.J.",
  "Methods in Molecular Biology 2968, 77–109 (2025)",
  L(("Journal", "https://link.springer.com/protocol/10.1007/978-1-0716-4750-9_5"))),
 (35, 2025, "Predicting cell cycle stage from 3D single-cell nuclear-stained images",
  "Li, G.*, Nichols, E.K.*, Browning, V.E., Longhi, N.J., Sanchez-Forman, M., Camplisson, C.K., Beliveau, B.J.†, Noble, W.S.†",
  "Life Science Alliance (2025)",
  L(("Journal", "https://www.life-science-alliance.org/content/8/6/e202403067.abstract"), ("PDF", "https://www.life-science-alliance.org/content/lsa/8/6/e202403067.full-text.pdf"), ("SI", "https://www.life-science-alliance.org/content/8/6/e202403067/tab-figures-data"))),
 (34, 2025, "Molecular Phenotyping With Proteomics",
  "Schweppe, D.K., Beliveau, B.J., Hoofnagle, A.N.",
  "JAMA (2025)",
  L(("Journal", "https://jamanetwork.com/journals/jama/fullarticle/2829804"), ("PDF", "https://jamanetwork.com/journals/jama/articlepdf/2829804/jama_schweppe_2025_it_240046_1738093159.52549.pdf"))),
 (33, 2024, "Efficient and highly amplified imaging of nucleic acid targets in cellular and histopathological samples with pSABER",
  "Attar, S., Browning, V.E., Krebs, M., Liu, Y., Nichols, E.K., Tsue, A.F., Shechner, D.M., Shendure, J., Lieberman, J.A., Schweppe, D.K., Akilesh, S.†, Beliveau, B.J.†",
  "Nature Methods (2024)",
  L(("Journal", "https://www.nature.com/articles/s41592-024-02512-2"), ("PDF", "https://rdcu.be/d0h5x"))),
 (32, 2024, "Multiomic characterization of RNA microenvironments by oligonucleotide-mediated proximity-interactome mapping",
  "Tsue, A.F., Kania, E.E., Lei, D.Q., Fields, R., McGann, C.D., Marciniak, D.M., Hershberg, E.A., Deng, X., Kihiu, M., Ong, S.E., Disteche, C.M., Kugel, S., Beliveau, B.J., Schweppe, D.K., Shechner, D.M.",
  "Nature Methods 21, 2058–2071 (2024)",
  L(("Journal", "https://www.nature.com/articles/s41592-024-02457-6"), ("PDF", "https://www.nature.com/articles/s41592-024-02457-6.pdf"), ("SI", "https://www.nature.com/articles/s41592-024-02457-6#Sec32"))),
 (31, 2024, "A guide to studying 3D genome structure and dynamics in the kidney",
  "Beliveau, B.J., Akilesh, S.",
  "Nature Reviews Nephrology (2024)",
  L(("Journal", "https://www.nature.com/articles/s41581-024-00894-2"), ("PDF", "https://www.nature.com/articles/s41581-024-00894-2.pdf"))),
 (30, 2024, "Designing Oligonucleotide-Based FISH Probe Sets with PaintSHOP",
  "Perez, M.W., Camplisson, C.K., Beliveau, B.J.",
  "Methods in Molecular Biology 2748, 177–189 (2024)",
  L(("Journal", "https://link.springer.com/protocol/10.1007/978-1-0716-3766-1_12"))),
 (29, 2024, "Tigerfish designs oligonucleotide-based in situ hybridization probes targeting intervals of highly repetitive DNA at the scale of genomes",
  "Aguilar, R., Camplisson, C.K., Lin, Q., Miga, K.H., Noble, W.S.†, Beliveau, B.J.†",
  "Nature Communications 15, 1027 (2024)",
  L(("Journal", "https://www.nature.com/articles/s41467-024-45385-x"), ("PDF", "https://www.nature.com/articles/s41467-024-45385-x.pdf"), ("SI", "https://static-content.springer.com/esm/art%3A10.1038%2Fs41467-024-45385-x/MediaObjects/41467_2024_45385_MOESM1_ESM.pdf"))),
 (28, 2023, "Spatial and temporal organization of the genome: Current state and future aims of the 4D nucleome project",
  "Dekker, J., Alber, F., Aufmkolk, S., Beliveau, B.J., Bruneau, B.G., Belmont, A.S., Bintu, L., Boettiger, A., et al.",
  "Molecular Cell 83 (2023)",
  L(("Journal", "https://www.cell.com/molecular-cell/fulltext/S1097-2765(23)00465-3"), ("PDF", "https://www.cell.com/action/showPdf?pii=S1097-2765%2823%2900465-3"))),
 (27, 2023, "Cohesin controls X chromosome structure remodeling and X-reactivation during mouse iPSC-reprogramming",
  "Generoso, S.F., Neguembor, M.V., Hershberg, E.A., Sadreyev, R.I., Kurimoto, K., Yabuta, Y., Ricci, R., Audergon, P., Bauer, M., Saitou, M., Hochedlinger, K., Beliveau, B.J., Cosma, M.P., Lee, J.T., Payer, B.",
  "Proc. Natl. Acad. Sci. USA 120, e2213810120 (2023)",
  L(("Journal", "https://www.pnas.org/doi/10.1073/pnas.2213810120"), ("PDF", "https://www.pnas.org/doi/epdf/10.1073/pnas.2213810120"), ("SI", "https://www.pnas.org/doi/10.1073/pnas.2213810120#supplementary-materials"))),
 (26, 2022, "Optimized single-nucleus transcriptional profiling by combinatorial indexing",
  "Martin, B.K., Qiu, C., Nichols, E.K., Phung, M., Green-Gladden, R., Srivatsan, S., Blecher-Gonan, R., Beliveau, B.J., Trapnell, C., Cao, J., Shendure, J.",
  "Nature Protocols (2022)",
  L(("PDF", "https://www.nature.com/articles/s41596-022-00752-0.pdf"), ("SI", "https://www.nature.com/articles/s41596-022-00752-0#Sec50"), ("arXiv", "https://arxiv.org/abs/2110.15400"))),
 (25, 2022, "An open source 16-channel fluidics system for automating sequential fluorescent in situ hybridization (FISH)-based imaging",
  "Deng, Z., Beliveau, B.J.",
  "HardwareX (2022)",
  L(("Journal", "https://doi.org/10.1016/j.ohx.2022.e00343"), ("bioRxiv", "https://www.biorxiv.org/content/10.1101/2022.03.23.485524v1"))),
 (24, 2022, "A hybrid open-top light-sheet microscope for multi-scale imaging of cleared tissues",
  "Glaser, A.K.†, Bishop, K.W., Barner, L.A., Susaki, E.A., Kubota, S.I., Gao, G., Serafin, R.B., Balaram, P., Turschak, E., Nicovich, P.R., Lai, H., et al., Beliveau, B.J., et al., Liu, J.T.C.†",
  "Nature Methods 19, 613–619 (2022)",
  L(("Journal", "https://www.nature.com/articles/s41592-022-01468-5"), ("PDF", "https://www.nature.com/articles/s41592-022-01468-5.pdf"), ("bioRxiv", "https://www.biorxiv.org/content/10.1101/2020.05.06.081745v2"))),
 (23, 2021, "PaintSHOP enables the interactive design of transcriptome- and genome-scale oligonucleotide FISH experiments",
  "Hershberg, E.A.*, Camplisson, C.K.*, Close, J.L., Attar, S., Chern, R., Liu, Y., Akilesh, S., Nicovich, P.R., Beliveau, B.J.",
  "Nature Methods 18, 937–944 (2021)",
  L(("Journal", "https://www.nature.com/articles/s41592-021-01187-3"), ("bioRxiv", "https://www.biorxiv.org/content/10.1101/2020.07.05.188797v1"))),
 (22, 2020, "3D mapping and accelerated super-resolution imaging of the human genome using in situ sequencing",
  "Nguyen, H.Q.*, Chattoraj, S.*, Castillo, D.*, Nguyen, S.C., Nir, G., Lioutas, A., Hershberg, E.A., Martins, N.M.C., Reginato, P.L., Hannan, M., Beliveau, B.J., Church, G.M., Daugharthy, E.R., Marti-Renom, M.A.†, Wu, C.-T.†",
  "Nature Methods 17, 822–832 (2020)",
  L(("Journal", "https://www.nature.com/articles/s41592-020-0890-0"), ("PDF", "https://www.nature.com/articles/s41592-020-0890-0.pdf"), ("SI", "https://static-content.springer.com/esm/art%3A10.1038%2Fs41592-020-0890-0/MediaObjects/41592_2020_890_MOESM1_ESM.pdf"))),
 (21, 2020, "Combining Qdot Nanotechnology and DNA Nanotechnology for Sensitive Single-Cell Imaging",
  "Zhou, W., Han, Y., Beliveau, B.J., Gao, X.",
  "Advanced Materials 32, 201908410 (2020)",
  L(("Journal", "https://onlinelibrary.wiley.com/doi/full/10.1002/adma.201908410"))),
 (20, 2020, "OligoMinerApp: a web-server application for the design of genome-scale oligonucleotide in situ hybridization probes through the flexible OligoMiner environment",
  "Passaro, M., Martinovic, M., Bevilacqua, V., Hershberg, E.A., Rossetti, G., Beliveau, B.J., Bonnal, R.J.P.†, Pagani, M.†",
  "Nucleic Acids Research, gkaa251 (2020)",
  L(("Journal", "https://academic.oup.com/nar/advance-article/doi/10.1093/nar/gkaa251/5822955"), ("PDF", "https://academic.oup.com/nar/article-pdf/doi/10.1093/nar/gkaa251/33106200/gkaa251.pdf"))),
 (19, 2020, "Pericentromeric heterochromatin is hierarchically organized and spatially contacts H3K9me2/3 islands in euchromatin",
  "Lee, Y.C.G.†, Ogiyama, Y., Martins, N.M.C., Beliveau, B.J., Acevedo, D., Wu, C.-T., Cavalli, G., Karpen, G.H.†",
  "PLoS Genetics 16, e1008673 (2020)",
  L(("Journal", "https://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1008673"), ("PDF", "https://journals.plos.org/plosgenetics/article/file?id=10.1371/journal.pgen.1008673&type=printable"), ("bioRxiv", "https://www.biorxiv.org/content/10.1101/525873v1"))),
 (18, 2019, "Rapid in vitro production of single-stranded DNA",
  "Minev, D.*, Guerra, R.*, Kishi, J.Y., Smith, C., Krieg, E., Said, K., Hornick, A., Sasaki, H.M., Filsinger, G., Beliveau, B.J., Yin, P., Church, G.M., Shih, W.M.",
  "Nucleic Acids Research, gkz998 (2019)",
  L(("Journal", "https://academic.oup.com/nar/advance-article/doi/10.1093/nar/gkz998/5622713"), ("bioRxiv", "https://www.biorxiv.org/content/10.1101/558429v1"))),
 (17, 2019, "Immuno-SABER enables highly multiplexed and amplified protein imaging in tissues",
  "Saka, S.K.*†, Wang, Y.*†, Kishi, J.Y., Zhu, A., Zeng, Y., Xie, W., Kirli, K., Yapp, C., Cicconet, M., Beliveau, B.J., Lapan, S.W., Yin, S., Lin, M., Boyden, E.S., Kaeser, P.S., Pihan, G., Church, G.M., Yin, P.†",
  "Nature Biotechnology 37, 1080–1090 (2019)",
  L(("Journal", "https://www.nature.com/articles/s41587-019-0207-y"), ("PDF", "https://yin.hms.harvard.edu/publications/2019.immuno-saber.pdf"), ("bioRxiv", "https://www.biorxiv.org/content/early/2018/12/28/507566"))),
 (16, 2019, "SABER amplifies FISH: enhanced multiplexed imaging of RNA and DNA in cells and tissues",
  "Kishi, J.Y.*, Lapan, S.W.*, Beliveau, B.J.*†, West, E.R.*, Zhu, A., Sasaki, H.M., Saka, S.K., Wang, Y., Cepko, C.L.†, Yin, P.†",
  "Nature Methods 16, 533–544 (2019)",
  L(("Journal", "https://www.nature.com/articles/s41592-019-0404-0"), ("PDF", "https://yin.hms.harvard.edu/publications/2019.saber.pdf"), ("bioRxiv", "https://www.biorxiv.org/content/early/2018/08/27/401810"))),
 (15, 2019, "Islands of retroelements are the major components of Drosophila centromeres",
  "Chang, C.H.*, Chavan, A.*, Palladino, J.*, Wei, X., Martins, N.M.C., Santinello, B., Chen, C.C., Erceg, J., Beliveau, B.J., Wu, C.-T., Larracuente, A.M.†, Mellone, B.†",
  "PLoS Biology 17, e3000241 (2019)",
  L(("Journal", "https://journals.plos.org/plosbiology/article?id=10.1371/journal.pbio.3000241"), ("PDF", "https://journals.plos.org/plosbiology/article/file?id=10.1371/journal.pbio.3000241&type=printable"), ("bioRxiv", "https://www.biorxiv.org/content/10.1101/537357v1"))),
 (14, 2018, "Walking along chromosomes with super-resolution imaging, contact maps, and integrative modeling",
  "Nir, G.*, Farabella, I.*, Pérez Estrada, C.*, Ebeling, C.G.*, Beliveau, B.J., Sasaki, H.M., Lee, S.H., Nguyen, S.C., McCole, R.B., Chattoraj, S., et al., Stuckey, J.A.†, Yin, P.†, Lieberman Aiden, E.†, Marti-Renom, M.A.†, Wu, C.-T.†",
  "PLoS Genetics 14, e1007872 (2018)",
  L(("Journal", "https://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1007872"), ("PDF", "https://journals.plos.org/plosgenetics/article/file?id=10.1371/journal.pgen.1007872&type=printable"), ("bioRxiv", "https://www.biorxiv.org/content/early/2018/07/28/374058"))),
 (13, 2018, "OligoMiner provides a rapid, flexible environment for the design of genome-scale oligonucleotide in situ hybridization probes",
  "Beliveau, B.J.†, Kishi, J.Y., Nir, G., Sasaki, H.M., Saka, S.K., Nguyen, S.C., Wu, C.-T., Yin, P.†",
  "Proc. Natl. Acad. Sci. USA 115, E2183–E2192 (2018)",
  L(("Journal", "http://www.pnas.org/content/115/10/E2183.long"), ("PDF", "http://www.pnas.org/content/pnas/115/10/E2183.full.pdf"), ("bioRxiv", "https://www.biorxiv.org/content/early/2017/08/16/171504"))),
 (12, 2017, "Multiplexed 3D super-resolution imaging of whole cells using Spinning Disc Confocal Microscopy and DNA-PAINT",
  "Schüder, F., Lara-Gutiérrez, J., Beliveau, B.J., Saka, S.K., Sasaki, H.M., Woehrstein, J.B., Strauss, M.T., Grabmayr, H., Yin, P., Jungmann, R.",
  "Nature Communications 8, 2090 (2017)",
  L(("Journal", "https://www.nature.com/articles/s41467-017-02028-8"), ("PDF", "https://www.nature.com/articles/s41467-017-02028-8.pdf"))),
 (11, 2017, "In situ super-resolution imaging of genomic DNA with OligoSTORM and OligoDNA-PAINT",
  "Beliveau, B.J.*, Boettiger, A.N.*, Nir, G.*, Bintu, B.*, Yin, P., Zhuang, X., Wu, C.-T.",
  "Methods in Molecular Biology 1663, 231–252 (2017)",
  L(("Journal", "https://link.springer.com/protocol/10.1007%2F978-1-4939-7265-4_19"), ("PDF", "https://yin.hms.harvard.edu/publications/2017.oligodnapaint.pdf"))),
 (10, 2016, "Spatial organization of chromatin domains and compartments in single chromosomes",
  "Wang, S., Su, J.H., Beliveau, B.J., Bintu, B., Moffitt, J.R., Wu, C.-T., Zhuang, X.",
  "Science 353, 598–602 (2016)",
  L(("Journal", "http://science.sciencemag.org/content/early/2016/07/20/science.aaf8084"), ("PDF", "http://science.sciencemag.org/content/early/2016/07/20/science.aaf8084.full.pdf"))),
 (9, 2016, "Super-resolution imaging reveals distinct chromatin folding for different epigenetic states",
  "Boettiger, A.N., Bintu, B., Moffitt, J.R., Wang, S., Beliveau, B.J., Fudenberg, G., Imakaev, M., Mirny, L.A., Wu, C.-T., Zhuang, X.",
  "Nature 529, 418–422 (2016)",
  L(("Journal", "https://www.nature.com/articles/nature16496"), ("PDF", "https://www.nature.com/articles/nature16496.pdf"))),
 (8, 2015, "Scalable amplification of single-stranded oligonucleotides from chip-synthesized oligonucleotide libraries",
  "Schmidt, T.L., Beliveau, B.J., Uca, Y.O., Theilmann, M., Da Cruz, F., Wu, C.-T., Shih, W.M.",
  "Nature Communications 6, 9634 (2015)",
  L(("Journal", "https://www.nature.com/articles/ncomms9634"), ("PDF", "https://www.nature.com/articles/ncomms9634.pdf"))),
 (7, 2015, "Single-molecule super-resolution imaging of chromosomes and in situ haplotype visualization using Oligopaint FISH probes",
  "Beliveau, B.J., Boettiger, A.B., Avendaño, M.S., Jungmann, R., McCole, R.B., Joyce, E.F., Kim-Kiselak, C., Bantignies, F., Fonseka, C.Y., Erceg, J., Hannan, M.A., Hoang, H.G., Colognori, D., Lee, J.T., Shih, W.M., Yin, P., Zhuang, X., Wu, C.-T.",
  "Nature Communications 6, 8147 (2015)",
  L(("Journal", "https://www.nature.com/articles/ncomms8147"), ("PDF", "https://www.nature.com/articles/ncomms8147.pdf"))),
 (6, 2015, "Allelic imbalance is a prevalent and tissue-specific feature of the mouse transcriptome",
  "Pinter, S.F., Colognori, D., Beliveau, B.J., Sadreyev, R.I., Payer, B., Yildirim, E., Wu, C.-T., Lee, J.T.",
  "Genetics 200, 537–549 (2015)",
  L(("Journal", "http://www.genetics.org/content/200/2/537"), ("PDF", "http://www.genetics.org/content/genetics/200/2/537.full.pdf"))),
 (5, 2015, "Combined in vitro transcription and reverse transcription to amplify and label complex synthetic oligonucleotide probe libraries",
  "Murgha, Y., Beliveau, B., Semrau, K., Schwartz, D., Wu, C.-T., Gulari, E., Rouillard, J.M.",
  "Biotechniques 58, 301–307 (2015)",
  L(("Journal", "https://www.future-science.com/doi/10.2144/000114298"), ("PDF", "https://www.future-science.com/doi/pdf/10.2144/000114298"))),
 (4, 2015, "Avoiding the Ends: Internal Epitope Tagging of Proteins Using Transposon Tn7",
  "Zordan, R.E., Beliveau, B.J., Trow, J.A., Craig, N.L., Cormack, B.P.",
  "Genetics 200, 47–58 (2015)",
  L(("Journal", "http://www.genetics.org/content/200/1/47.long"), ("PDF", "http://www.genetics.org/content/genetics/200/1/47.full.pdf"))),
 (3, 2014, "Visualizing genomes with Oligopaint FISH probes",
  "Beliveau, B.J., Apostolopoulos, N.A., Wu, C.-T.",
  "Current Protocols in Molecular Biology 105, Unit 14.23 (2014)",
  L(("Journal", "https://currentprotocols.onlinelibrary.wiley.com/doi/pdf/10.1002/0471142727.mb1423s105"))),
 (2, 2013, "Germline progenitors escape the widespread phenomenon of homolog pairing during Drosophila development",
  "Joyce, E.F., Apostolopoulos, N., Beliveau, B.J., Wu, C.-T.",
  "PLoS Genetics 9, e1004013 (2013)",
  L(("Journal", "https://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1004013"), ("PDF", "https://journals.plos.org/plosgenetics/article/file?id=10.1371/journal.pgen.1004013&type=printable"))),
 (1, 2012, "Versatile design and synthesis platform for visualizing genomes with Oligopaint FISH probes",
  "Beliveau, B.J.*, Joyce, E.F.*, Apostolopoulos, N., Yilmaz, F., Fonseka, C.Y., McCole, R.B., Chang, Y., Li, J.B., Senaratne, T.N., Williams, B.R., Rouillard, J.M., Wu, C.-T.",
  "Proc. Natl. Acad. Sci. USA 109, 21301–21306 (2012)",
  L(("Journal", "http://www.pnas.org/content/109/52/21301"), ("PDF", "http://www.pnas.org/content/pnas/109/52/21301.full.pdf"))),
]

papers_out = [{"num": n, "year": y, "title": t, "authors": a, "venue": v, "links": l}
              for (n, y, t, a, v, l) in papers]

data = {"preprints": preprints, "papers": papers_out,
        "scholar": "https://scholar.google.com/citations?user=whBdHk8AAAAJ&hl=en",
        "pubmed": "https://www.ncbi.nlm.nih.gov/pubmed?term=((beliveau%20B%5BAuthor%5D%20OR%20beliveau%20BJ%5BAuthor%5D))%20AND%20(%222012%22%5BDate%20-%20Publication%5D%20%3A%20%223000%22%5BDate%20-%20Publication%5D)"}
out = pathlib.Path(__file__).resolve().parent.parent / "data" / "publications.json"
out.write_text(json.dumps(data, indent=2, ensure_ascii=False))
print(f"Wrote {out} — {len(preprints)} preprints, {len(papers_out)} papers")
